### ISSUE TITLE
ActiveResource expectations for form of error message? How to coerce non-standard error into that form?

### ISSUE THREAD

**Issue by cmarkle** [rails/activeresource#116]
I am accessing the Zendesk v2 API with ActiveResource. Today I tried to update via PUT a resource where I used a name that already existed. This returned HTTP 422 and the following JSON:

-> "{\"error\":\"RecordInvalid\",\"description\":\"Record validation errors\",\"details\":{\"name\":[{\"description\":\"Name has already been taken\"}]}}"

--or--

```
{
    "error"; "RecordInvalid",
    "description": "Record validation errors",
    "details": {
        "name": [ 
            { "description": "Name has already been taken" }
        ]
    }
}
```

This resulted in the following exception:

```
I, [2014-01-10T13:48:07.866954 #3813]  INFO -- : PUT 
    https://support.asperasoft.com:443/api/v2/organizations/20151598.json
I, [2014-01-10T13:48:07.867280 #3813]  INFO -- : --> 
    422 Unprocessable Entity 133 (517.5ms)
DEPRECATION WARNING: Returning errors as a hash without a 
    root "errors" key is deprecated. 
    (called from update_org at ./update_zen_orgs_from_sfdc.rb:289)
/usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:37:in `block in from_hash': 
    undefined method `each' for "RecordInvalid":String (NoMethodError)
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:36:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:36:in `from_hash'
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:67:in `from_json'
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:138:in `load_remote_errors'
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:126:in `rescue in save_with_validation'
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/validations.rb:109:in `save_with_validation'
        from /usr/local/rvm/gems/ruby-1.9.3-p484/gems/activeresource-4.0.0/lib/active_resource/observing.rb:21:in `save_with_notifications'
        from ./update_zen_orgs_from_sfdc.rb:289:in `update_org'
        from ./update_zen_orgs_from_sfdc.rb:511:in `block in <main>'
        from ./update_zen_orgs_from_sfdc.rb:301:in `each'
        from ./update_zen_orgs_from_sfdc.rb:301:in `<main>'
```

Two questions about this;
1. Looks like AactiveResource is looking for error infgor to be a hash with a root "errors" key. What exactly is the expected format for the error info and where is this documented?
2. Is there a way with ActiveResource where I can coerce this non-standard error JSON into something that AR would be happy with?

Thanks in advance for any help here...

**Comment by nathanwfish** [comment]
@mriddle would you mind sharing more of your solution? I'm running into the same issue and interested in how you solved it.

**Comment by rafaelfranca** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least three months.

The resources of the Rails team are limited, and so we are asking for your help.

If it is an issue and you can still reproduce this error on the `master` branch,  please reply with all of the information you have about it in order to keep the issue open.

If it is a pull request and you are still interested on having it merged please make sure it can be merged clearly.

Thank you for all your contributions.

**Comment by lancecarlson** [comment]
Should this be a more explicitly documented thing? Perhaps even a "callback" or method you can override to customize error parsing? I think there is a frequent enough use case here. Most API's have their own way of returning errors.

**Comment by muxcmux** [comment]
For anyone looking for a solution for AR 5.1 - overriding the initializer doesn't do it. You either have to monkey-patch `ActiveResource::Errors#from_json` method or extend that and return an instance of your own class in `ActiveResource::Validations#errors` (`ActiveResource::Validations` is mixed into `ActiveResource::Base`, so simply overwrite `errors` method.

**Comment by bowtiesolutions** [comment]
You can achieve this by overriding the 'load_remote_errors' method in recent versions and preprocessing the response body.

For a response body like:

```
{
  "errors": [
    {
      "path": "/Status",
      "message": "Project status code not found.",
      "value": 0
    }
  ]
}
```

You could modify the body to fit the expected format of an array of strings for errors, instead of an array of hashes:

```
class Resource < ActiveResource::Base
  schema do

  end

  def load_remote_errors(remote_errors, save_cache = false) # :nodoc:
    case self.class.format
    when ActiveResource::Formats[:xml]
      errors.from_xml(remote_errors.response.body, save_cache)
    when ActiveResource::Formats[:json]
      decoded = ActiveSupport::JSON.decode(remote_errors.response.body) || {} rescue {}
      decoded["errors"] = decoded["errors"].map {|error| error["message"]} rescue ["Unprocessable Entity"]
      errors.from_json(decoded.to_json, save_cache)
    end
  end

  private

end
```
