### ISSUE TITLE
Tests currently fail on master due to missing `builder` gem dependency.

### ISSUE THREAD

**Issue by phil** [rails/activeresource#204]
example failing test:

```
SchemaTest#test_schema_should_accept_all_known_attribute_types_as_values:
LoadError: cannot load such file -- builder
    /Users/phil/.gem/ruby/2.2.2/bundler/gems/rails-473f63734a55/activesupport/lib/active_support/builder.rb:2:in `require'
    /Users/phil/.gem/ruby/2.2.2/bundler/gems/rails-473f63734a55/activesupport/lib/active_support/builder.rb:2:in `<top (required)>'
    /Users/phil/.gem/ruby/2.2.2/bundler/gems/rails-473f63734a55/activesupport/lib/active_support/core_ext/hash/conversions.rb:75:in `require'
    /Users/phil/.gem/ruby/2.2.2/bundler/gems/rails-473f63734a55/activesupport/lib/active_support/core_ext/hash/conversions.rb:75:in `to_xml'
    /Users/phil/Workspace/forks/activeresource/test/abstract_unit.rb:23:in `setup_response'
    /Users/phil/Workspace/forks/activeresource/test/cases/base/schema_test.rb:11:in `setup'
```

**Comment by rafaelfranca** [comment]
All tests are now passing on master. Let us know if that is not the case.
