### ISSUE TITLE
Unable to use without ActiveRecord

### ISSUE THREAD

**Issue by ball-hayden** [rails/activeresource#210]
I'm not sure if this is more a bug with ActiveResource, or with Rails Observers, but I think here seems more appropriate.

ActiveResource depends on `rails-observers`. When running in production mode (or, indeed, any mode with eager loading enabled), an application that doesn't load ActiveRecord will fail:

```
uninitialized constant ActionController::Caching::ActiveRecord (NameError)
    from /home/hayden/.rvm/gems/ruby-2.2.4/bundler/gems/rails-observers-bca5db98e2e8/lib/rails/observers/action_controller/caching/sweeper.rb:2:in `<module:ActionController>'
    from /home/hayden/.rvm/gems/ruby-2.2.4/bundler/gems/rails-observers-bca5db98e2e8/lib/rails/observers/action_controller/caching/sweeper.rb:1:in `<top (required)>'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies/autoload.rb:70:in `block in eager_load!'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies/autoload.rb:70:in `each_value'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies/autoload.rb:70:in `eager_load!'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/actionpack-5.0.0.beta2/lib/action_controller.rb:53:in `eager_load!'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/railties-5.0.0.beta2/lib/rails/application/finisher.rb:56:in `each'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/railties-5.0.0.beta2/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `run'
    from /home/hayden/.rvm/gems/ruby-2.2.4/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:55:in `block in run_initializers'
...
```

I may be misunderstanding, but is Rails Observers a production dependency, or just required for tests?

**Comment by rafaelfranca** [comment]
This is fixed on the master branch.
