### ISSUE TITLE
ActiveResource::HttpMock not allowing for headers

### ISSUE THREAD

**Issue by ojsdude** [rails/activeresource#284]
I have tried to add ActiveResource::HttpMock to my rspec tests and have the following code inside my `before` block:
```
req_headers = {
  "Authorization"=>"Basic RandomStringAuth==",
  "Accept"=>"application/json"
}
ActiveResource::HttpMock.respond_to do |mock|
  mock.get "/people.json?goldmine_customer_number=321", req_headers, "[#{fake_person}]", 200, "Location" => "/people/1.json"
  mock.get "/people/123.json", req_headers, fake_person, 200, "Location" => "/people/1.json"
end
```
When I run my tests I get errors as follows:

```
1) RegistrationsController#create when signed in as a user when registering from the reference number email when the customer reference number is present and is valid redirects to the root path
     Failure/Error: found = where(attributes)

ActiveResource::InvalidRequestError:
       Could not find a response recorded for <GET: /people.json?goldmine_customer_number=321 [{"Authorization"=>"Basic RandomStringAuth==", "Accept"=>"application/json"}] ()> - Responses recorded are: ["<GET: /people.json?goldmine_customer_number=321 [{\"Authorization\"=>\"Basic RandomStringAuth==\\n\", \"Accept\"=>\"application/json\"}] ()>", "<GET: /people/123.json [{\"Authorization\"=>\"Basic RandomStringAuth==\\n\", \"Accept\"=>\"application/json\"}] ()>"]
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/http_mock.rb:264:in `get'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/connection.rb:131:in `block in request'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/connection.rb:128:in `request'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/connection.rb:92:in `block in get'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/connection.rb:228:in `with_auth'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/connection.rb:92:in `get'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/base.rb:1012:in `find_every'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/base.rb:919:in `find'
     # /Users/oj/.rvm/gems/ruby-2.2.2/gems/activeresource-4.1.0/lib/active_resource/base.rb:950:in `where'
```

It seems like `to_s` or something is being run on them so they never match?

**Comment by millenniumiguana** [comment]
I am running into the same issue, also rspec, also using a before block.

**Comment by devsdevsdevs** [comment]
Having the same error, using Cucumber

**Comment by devsdevsdevs** [comment]
@ojsdude Any fix?

**Comment by ravi-bebble** [comment]
Having same Issue, any fix?
