### ISSUE TITLE
Undefined method 'new' for Filters Module

### ISSUE THREAD

**Issue by ravi-bebble** [rails/activeresource#363]
I am using ActiveResource to integrate with Rossum and one of their API response includes filters as a key and its value is hash 

```
{
  "id": 1234,
  "name": "Receipts",
  "url": "https://api.elis.rossum.ai/v1/inboxes/1234",
  "queues": [
    "https://api.elis.rossum.ai/v1/queues/8199"
  ],
  "email": "east-west-trading-co-a34f3a@elis.rossum.ai",
  "email_prefix": "east-west-trading-co",
  "bounce_email_to": "bounces@east-west.com",
  "bounce_unprocessable_attachments": false,
  "bounce_deleted_annotations": false,
  "bounce_email_with_no_attachments": true,
  "metadata": {},
  "filters": {
    "allowed_senders": ["*@rossum.ai", "john.doe@company.com", "john.doe@company.??"],
    "denied_senders": ["spam@*"]
  }
}
```
ref: [to rossum api](https://api.elis.rossum.ai/docs/#inbox)

Setup of class

```
class RossumInbox < ActiveResource::Base
  self.site = 'https://api.elis.rossum.ai/v1'
  self.user = ENV['ROSSUM_USERNAME']
  self.password = ENV['ROSSUM_PASSWORD']
  self.include_format_in_path = false
  self.collection_parser = RossumCollection
  self.element_name = 'inbox'
end

class RossumCollection < ActiveResource::Collection
  attr_accessor :pagination, :extra_info
  def initialize(parsed = {})
    @elements = parsed['results']
    @next_page = parsed['pagination']
    @extra_info = parsed.except('results', 'pagination')
  end
end
```
The call I use to make a post request

```
@rossum_inbox = RossumInbox.create({
        name: "#{billable_company.name} - Invoice Inbox",
        email_prefix: @email_prefix || billable_company.name.parameterize,
        bounce_email_to: billable_company.email,
        queues: [rossum_queue.url]
      })
```

I got the error as 

```
##############################################INFO##############################################
{
  "method": "post",
  "request_uri": "https://api.elis.rossum.ai:443/v1/inboxes",
  "http_status": "201",
  "http_message": "Created"
}
##############################################INFO##############################################
Completed 500 Internal Server Error in 7966ms (ActiveRecord: 54.9ms)


  
NoMethodError (undefined method `new' for Filters:Module):
  
app/src/billable_companies/integrate_with_rossum_service.rb:33:in `create_rossum_inbox'
app/src/billable_companies/integrate_with_rossum_service.rb:27:in `create_rossum_entities'
app/src/billable_companies/integrate_with_rossum_service.rb:13:in `run'
app/facades/rossum_inboxes/create_facade.rb:22:in `integrate_with_rossum'
app/facades/rossum_inboxes/create_facade.rb:5:in `run'
app/controllers/application_controller.rb:9:in `run'
app/controllers/rossum_inboxes_controller.rb:3:in `create'
```
On checking rails console I could see Filters Module
` Filters.ancestors  #=> [Filters] `

I have temporarily avoided it by  overriding find_or_create_resource_for method inside the class

```

  def find_or_create_resource_for(name)
    return reflections[name.to_sym].klass if reflections.key?(name.to_sym)
    resource_name = name.to_s.camelize

    const_args = [resource_name, false]

    if !const_valid?(*const_args) || name == :filters
      # resource_name is not a valid ruby module name and cannot be created normally
      find_or_create_resource_for(:UnnamedResource)
    elsif self.class.const_defined?(*const_args)
      self.class.const_get(*const_args)
    else
      ancestors = self.class.name.to_s.split("::")
      if ancestors.size > 1
        find_or_create_resource_in_modules(resource_name, ancestors)
      else
        if Object.const_defined?(*const_args)
          Object.const_get(*const_args)
        else
          create_resource_for(resource_name)
        end
      end
    end
  end
```

Simply Added an or condition.

Gem version: (5.1.1)
Rails version: (5.2.6)

**Comment by Volosh1n** [comment]
Hi! I think this is because ActiveResource tries to create an object for each key from JSON. In your case, you have 'filters' and yes, you already patched the way AR treats those fields with that 'or' statement. Recently I faced almost the same issue (at least `find_or_create_resource_for` didn't work as I wanted) and defining something like `has_many :filters`(my entities have another name, just an example) did the trick. Maybe you will have to provide some custom class for this association and do something like:

```ruby
class RossumInbox < ActiveResource::Base
  self.site = 'https://api.elis.rossum.ai/v1'
  self.user = ENV['ROSSUM_USERNAME']
  self.password = ENV['ROSSUM_PASSWORD']
  self.include_format_in_path = false
  self.collection_parser = RossumCollection
  self.element_name = 'inbox'

  has_many :filters, class_name: 'YourCustomClassForFilter'
end

class YourCustomClassForFilter < ActiveResource::Base
end
```

Hope I gave direction to understanding.

**Comment by ravi-bebble** [comment]
Hello @Volosh1n!

Thanks for the response! I already tried that but the issue with that is, we already have a module named Filters from ActiveSupport [check here](https://api.rubyonrails.org/v4.1.0/classes/ActiveSupport/Callbacks/Filters.html)
