### ISSUE TITLE
undefined method `alias_method_chain' for ActiveResource::Base:Class

### ISSUE THREAD

**Issue by coding-bunny** [rails/activeresource#374]
Hello,

I'm running into something of a weird behavior with this gem under specific conditions.
We're using ActiveResource as a dependency alongside ActiveSupport for a client gem of ours, and support Ruby versions 2.5 -> 3.0.

On Ruby 2.5 and 2.6, the client gem works without any problems, but for Ruby 2.7 and 3.0, I'm getting the following issue:

```
An error occurred while loading ./spec/deployment_history_client/deployment_spec.rb.
Failure/Error:
  class Base < ::ActiveResource::Base
    # Set the Authentication header to allow remote calls to be accepted by the service
    headers['Authorization'] = "Token token=#{::DeploymentHistoryClient.config.token}"
    self.site =  "#{::DeploymentHistoryClient.config.url}/api/v1"
    self.timeout = 30

NoMethodError:
  undefined method `alias_method_chain' for ActiveResource::Base:Class
  Did you mean?  alias_method
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/observing.rb:27:in `block (2 levels) in <module:Observing>'
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/observing.rb:9:in `each'
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/observing.rb:9:in `block in <module:Observing>'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/concern.rb:136:in `class_eval'
# ./vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/concern.rb:136:in `append_features'
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:1557:in `include'
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:1557:in `<class:Base>'
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:1553:in `<module:ActiveResource>'
# ./vendor/bundle/ruby/2.7.0/gems/activeresource-4.0.0.beta1/lib/active_resource/base.rb:22:in `<top (required)>'
# ./lib/deployment_history_client/base.rb:6:in `require'
# ./lib/deployment_history_client/base.rb:6:in `<module:DeploymentHistoryClient>'
# ./lib/deployment_history_client/base.rb:3:in `<top (required)>'
# ./lib/deployment_history_client/deployment.rb:11:in `require'
# ./lib/deployment_history_client/deployment.rb:11:in `<module:DeploymentHistoryClient>'
# ./lib/deployment_history_client/deployment.rb:5:in `<top (required)>'
# ./spec/deployment_history_client/deployment_spec.rb:3:in `require'
# ./spec/deployment_history_client/deployment_spec.rb:3:in `<top (required)>'


Top 0 slowest examples (0 seconds, 0.0% of total time):

Finished in 0.00006 seconds (files took 0.87198 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

Coverage report generated for RSpec to /app/coverage. 38 / 87 LOC (43.68%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected

Exited with code exit status 1
```

This is only happening in those 2 specific Ruby versions, and what I do not understand is why it's using the `4.0.0.beta1` version in these conditions. When i check out the code locally, and verify the version of the gem, I have the following:

```
bundle info activeresource
  * activeresource (5.1.1)
        Summary: REST modeling framework (part of Rails).
        Homepage: http://www.rubyonrails.org
        Path: /Users/olivar/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activeresource-5.1.1
```

The dependencies are defined as follows:

```
spec.add_dependency('activeresource', '>= 3.2.12')
spec.add_dependency('activesupport', '>= 3.2.12', '< 8')
spec.add_dependency('aws-sdk-sqs', '~> 1.39')
spec.add_dependency('oj', '~> 3.11')
```

When I switch locally to Ruby 3.0.0, and remove the `Gemfile.lock`, it also installs the 4.0.0.beta1 there.

**Comment by rafaelfranca** [comment]
I don't think this is an issue in this gem. It is either RubyGems or Bundler
